### ISSUE TITLE
Fix for Outbound Socket Mode

### ISSUE THREAD

**Issue by Netzvamp** [Otoru/Genesis#16]
The quickstart example for the "Outbound Socket Mode" in python 3.10 throws an `AttributeError: 'coroutine' object has no attribute 'wait'` and `RuntimeWarning: coroutine 'Session._awaitable_complete_command' was never awaited
  handle = None  # Needed to break cycles when an exception occurs.` exception. I've tried to fix it and it seems to work (although i know basically nothing about asyncio :P ).

https://github.com/Otoru/Genesis/blob/d734d959b9b6a2ad6f58415cf787f367237fe80a/genesis/outbound.py#L100

changed to

`command_is_complete = await self._awaitable_complete_command("playback")`

Edit: The same on line 129 and 180, to get "say" and "play_and_get_digits" working.

**Comment by Otoru** [comment]
Thanks for the report.
I applied the suggested fix and I'm releasing a new version where this should no longer occur.

**Comment by Otoru** [comment]
Version 0.3.5 released
